name: Build And Publish

on:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install And Configure Poetry
        run: |
          python -m pip install --upgrade poetry
          poetry config virtualenvs.create false
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build And Publish To PyPI
        run: |
          poetry sync --without dev
          poetry build
          poetry publish
